import {
	type Icon,
	ArrowLeftRight,
	ArrowRightLeft,
	ArrowUpDown,
	Award,
	BarChart3,
	BookText,
	Box,
	Briefcase,
	Building2,
	Calculator,
	Calendar,
	CheckSquare,
	CircleDollarSign,
	ClipboardCheck,
	ClipboardList,
	DollarSign,
	Download,
	Droplet,
	Droplets,
	FileBarChart,
	FileText,
	Filter,
	Gift,
	Heart,
	History,
	Layers,
	LayoutDashboard,
	LayoutGrid,
	LayoutList,
	ListCheck,
	NotebookText,
	Package,
	PackageMinus,
	PackageOpen,
	Pill,
	QrCode,
	Receipt,
	Repeat,
	RotateCcw,
	Ruler,
	Send,
	Settings,
	SlidersHorizontal,
	Sprout,
	Star,
	Stethoscope,
	TrendingUp,
	Truck,
	Umbrella,
	Undo2,
	Upload,
	UserCircle,
	Users,
	UsersRound,
	Wallet,
	Warehouse,
	House,
	UserCog,
	UserRoundPen,
	Dock,
	Database,
	Folder,
	CreditCard,
	CreditCardIcon,
	Clock,
	Syringe
} from 'lucide-svelte';

export type LucideIconType = typeof Icon;

export const allMenus = {
	arrowLeft: ArrowLeftRight,
	arrowRight: ArrowRightLeft,
	arrowUp: ArrowUpDown,
	award: Award,
	barChart: BarChart3,
	book: BookText,
	box: Box,
	briefcase: Briefcase,
	building: Building2,
	calculator: Calculator,
	calendar: Calendar,
	checkSquare: CheckSquare,
	circleDollarSign: CircleDollarSign,
	clipboardCheck: ClipboardCheck,
	clipboardList: ClipboardList,
	dollarSign: DollarSign,
	download: Download,
	droplet: Droplet,
	droplets: Droplets,
	fileBarChart: FileBarChart,
	fileText: FileText,
	filter: Filter,
	gift: Gift,
	heart: Heart,
	history: History,
	house: House,
	layers: Layers,
	layoutDashboard: LayoutDashboard,
	layoutGrid: LayoutGrid,
	layoutList: LayoutList,
	listCheck: ListCheck,
	notebookText: NotebookText,
	package: Package,
	packageMinus: PackageMinus,
	packageOpen: PackageOpen,
	pill: Pill,
	qrCode: QrCode,
	receipt: Receipt,
	repeat: Repeat,
	rotateCcw: RotateCcw,
	ruler: Ruler,
	send: Send,
	settings: Settings,
	slidersHorizontal: SlidersHorizontal,
	sprout: Sprout,
	star: Star,
	stethoscope: Stethoscope,
	trendingUp: TrendingUp,
	truck: Truck,
	umbrella: Umbrella,
	undo2: Undo2,
	upload: Upload,
	userCircle: UserCircle,
	users: Users,
	usersRound: UsersRound,
	wallet: Wallet,
	warehouse: Warehouse,
	'user-cog': UserCog,
	'user-round-pen': UserRoundPen,
	dock: Dock,
	database: Database,
	folder: Folder,
	creditCard: CreditCard,
	creditCardIcon: CreditCardIcon,
	clock: Clock,
	syringe: Syringe
} as const;

export type MenuKey = keyof typeof allMenus;

export const menuKeys = Object.keys(allMenus);

export const getMenuIcon = (key?: MenuKey | (string & {})): typeof Icon => {
	return allMenus[key as MenuKey] || House;
};
