#!/usr/bin/env bun
/* eslint-disable @typescript-eslint/no-explicit-any */

import { writeFileSync, mkdirSync } from 'fs';
import { resolve } from 'path';
import { parseArgs } from 'util';
import { jsonSchemaToZod } from 'json-schema-to-zod';
import jsonRefs from 'json-refs';
import { services, defaultConfig } from './openapi.config';

// Types
interface OpenAPISpec {
	components?: {
		schemas?: Record<string, any>;
	};
	[key: string]: any;
}

interface CliArgs {
	service?: string; // Optional: generate only for specific service
	help?: boolean;
}

// Parse CLI arguments
const { values } = parseArgs({
	options: {
		service: { type: 'string', short: 's' },
		help: { type: 'boolean', short: 'h' }
	}
}) as { values: CliArgs };

if (values.help) {
	console.log(`
Usage: bun run generate-api.ts [options]

Options:
  -s, --service <name>   Generate only for specific service (matches 'name' in config)
  -h, --help             Show help

Configured Services:
${services.map((s) => `  - ${s.name}: ${s.source}`).join('\n')}
  `);
	process.exit(0);
}

// Helper: Fetch OpenAPI spec
async function fetchOpenAPISpec(source: string): Promise<OpenAPISpec> {
	console.log(`   📥 Fetching from ${source}...`);

	try {
		if (source.startsWith('http://') || source.startsWith('https://')) {
			const response = await fetch(source);
			if (!response.ok) {
				throw new Error(`HTTP ${response.status}: ${response.statusText}`);
			}
			return await response.json();
		} else {
			const file = Bun.file(source);
			return await file.json();
		}
	} catch (error) {
		console.error(`   ❌ Failed to fetch spec: ${(error as Error).message}`);
		throw error;
	}
}

// Helper: Generate Types
async function generateTypes(source: string, outputFile: string): Promise<void> {
	try {
		const cmd = ['bunx', 'openapi-typescript', source, '-o', outputFile];
		// console.log(`   Running: ${cmd.join(' ')}`);

		const proc = Bun.spawn(cmd, {
			stdout: 'pipe', // Suppress noisy output unless error? or just pipe to inherit
			stderr: 'inherit'
		});

		await proc.exited;

		if (proc.exitCode !== 0) {
			throw new Error(`openapi-typescript exited with code ${proc.exitCode}`);
		}
	} catch (error) {
		console.error(`   ❌ Failed to generate types: ${(error as Error).message}`);
		throw error;
	}
}

// Helper: Generate Zod Schemas
async function generateZodSchemas(openapi: OpenAPISpec, outputFile: string): Promise<void> {
	const schemas = openapi.components?.schemas || {};
	const schemaCount = Object.keys(schemas).length;

	if (schemaCount === 0) {
		console.warn('   ⚠️  No schemas found in components.schemas');
		return;
	}

	console.log(`   Resolving ${schemaCount} schemas...`);

	// Resolve all $ref references
	const { resolved } = await jsonRefs.resolveRefs(openapi);
	const resolvedSchemas = (resolved as OpenAPISpec)?.components?.schemas || {};

	let output = `import { z } from 'zod';\n\n`;
	let successCount = 0;
	let failCount = 0;

	for (const [name, schema] of Object.entries(resolvedSchemas)) {
		const sanitized = sanitizeSchemaName(name);
		try {
			if (isGenericResponseSchema(name)) {
				console.log(`      ⏭️  Skipping generic response schema: ${name}`);
				continue;
			}
			const zodSchemaString = jsonSchemaToZod(schema, {
				module: 'esm',
				name: `${sanitized}Schema`
			});

			const schemaDefinition = zodSchemaString
				.replace(/import\s+{\s*z\s*}\s+from\s+['"]zod['"];?\s*/g, '')
				.trim();

			output += `// ${sanitized}\n`;
			output += `${schemaDefinition}\n\n`;
			// output += `export type ${name} = z.infer<typeof ${name}Schema>;\n\n`; // types are already generated by openapi-typescript
			successCount++;
		} catch (error) {
			console.warn(`      ⚠️  Failed to generate ${sanitized}:`, (error as Error).message);
			failCount++;
		}
	}

	writeFileSync(outputFile, output);
	console.log(`   ✅ Generated ${successCount} Zod schemas (${failCount} failed)`);
}

// Helper: Format
async function formatFiles(files: string[]): Promise<void> {
	console.log('   ✨ Formatting...');
	try {
		const prettier = await import('prettier');
		for (const file of files) {
			try {
				const content = await Bun.file(file).text();
				const formatted = await prettier.format(content, { filepath: file });
				writeFileSync(file, formatted);
			} catch {
				console.warn(`      ⚠️  Failed to format ${file}`);
			}
		}
	} catch {
		console.warn('   ⚠️  Prettier import failed');
	}
}

async function processService(service: { name: string; source: string; outputDir?: string }) {
	console.log(`\n🚀 Processing Service: [${service.name}]`);

	const outputDir = service.outputDir
		? resolve(service.outputDir)
		: resolve(defaultConfig.baseOutputDir, service.name);

	const typesFile = resolve(outputDir, defaultConfig.typesFile);
	const schemasFile = resolve(outputDir, defaultConfig.schemasFile);

	mkdirSync(outputDir, { recursive: true });

	try {
		// 1. Fetch
		const openapi = await fetchOpenAPISpec(service.source);

		// 2. Types
		await generateTypes(service.source, typesFile);

		// 3. Schemas
		await generateZodSchemas(openapi, schemasFile);

		// 4. Format
		await formatFiles([typesFile, schemasFile]);

		console.log(`   ✅ Complete!`);
		console.log(`      Types:   ${typesFile}`);
		console.log(`      Schemas: ${schemasFile}`);
	} catch {
		console.error(`   ❌ Failed to process service ${service.name}`);
		// Don't exit process, just fail this service? Or exit?
		// Let's fail hard for now if this is CI/CD, but for dev maybe soft?
		// script usually fails if one fails.
		process.exitCode = 1;
	}
}

function sanitizeSchemaName(name: string): string {
	try {
		const sanitized = name.replace(/[^a-zA-Z0-9_]/g, '_');
		const PascalCase = sanitized.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
		return PascalCase;
	} catch (error) {
		console.error(`Failed to sanitize schema name: ${name}`, error);
		return name;
	}
}

// Main
async function main() {
	const targetServices = values.service
		? services.filter((s) => s.name === values.service)
		: services;

	if (targetServices.length === 0) {
		console.error(`No service found matching "${values.service}"`);
		process.exit(1);
	}

	const startTime = Date.now();

	// await Promise.all(targetServices.map(async (service) => processService(service))); // Race Condition
	for (const service of targetServices) {
		await processService(service);
	}

	const duration = ((Date.now() - startTime) / 1000).toFixed(2);
	if (!process.exitCode) {
		console.log(`\n🎉 All done in ${duration}s`);
	} else {
		console.log(`\n⚠️  Completed with errors in ${duration}s`);
	}
}

function isGenericResponseSchema(name: string): boolean {
	return name.includes('{}') || name.startsWith('APIResponse') || name.endsWith('DataStruct');
}

main();
